### ISSUE TITLE
Disabled rates

### ISSUE THREAD

**Issue by Notilix** [Hopperpop/Sgp4-Library#3]
Hi,
Thank you for this library. I'm planning to use it for my upcoming project related to the ISS.
I was wondering why did you comment all the code related to rates and velocity?
Have you had trouble to make it work on ESP? Or maybe it is due to performance considerations?
Do you think I can safely uncomment those lines to get the rates back?

Thank you

**Comment by Notilix** [comment]
I uncommented the lines and it seems stable.

**Comment by Hopperpop** [comment]
My original project didn't use the rates and it was disabled to increase performance. Mainly for doing predictions for the next overpass, as it's an iterative algorithm. Enabling should indeed not give any problems.
