### ISSUE TITLE
Compile error example SGP4Predictor

### ISSUE THREAD

**Issue by BoJack62** [Hopperpop/Sgp4-Library#4]
Receive “‘int min’ redeclared as a different type of symbol” error when compiling the SGP4 predictor example using either Arduino IDE or Web editor.

**Comment by Hopperpop** [comment]
Thanks for notifing. Fix is in b55a37214c151e623a38e93135db49096a6a9c50 (and 2bc276b222f9cf201d44d797402dadd7ddf536c6 for the other example).
